### ISSUE TITLE
Button covers the whole screen

### ISSUE THREAD

**Issue by kiwo12345** [xhamr/fave-button#10]
Once the VC opens the button covers the whole screen. I dont get any constraint errors either and I have a fixed width and height. I am using swift 3 and xcode 8.

No Idea whats causing this :/

<img width="320" alt="screen shot 2016-10-07 at 04 10 12" src="https://cloud.githubusercontent.com/assets/10579811/19176857/5a54ab24-8c44-11e6-8bd8-61df27aea9cd.png">

**Comment by lebomorojele** [comment]
+1

**Comment by janselv** [comment]
There are a few known issues reported for the official release of xcode 8.0 related to breaking layouts, I ran the demo project in xcode 8.1-beta and the issue seem to be fixed, try download and test it in that version. from [here](https://developer.apple.com/download/)

**Comment by kiwo12345** [comment]
@xhamr lowering the constraint priority to something bellow 1000 and adding layoutifneeded() seems to fix it

**Comment by janselv** [comment]
Thanks @kiwo12345,

**Comment by kunalverma25** [comment]
Still getting the same thing!!!

**Comment by janselv** [comment]
@kunalverma25 have you tried these two ways above?

**Comment by kunalverma25** [comment]
Yup...
Button was in a stackview..
Height set to 50..
Priority to 750
Called button's layoutifneeded in view did load func..
Still getting the same thing..

**Comment by ws4715535** [comment]
errr, i am getting the same thing!
i found a strange thing ,
If i set autoLayout to the button, it will cover the whole screen. When i remove the constrains , it will be ok  ..

**Comment by janselv** [comment]
I built the demo project again under the new revision of xcode 8 beta-3 and still worked, but going back to the oficial release of xcode 8, the problem is still there. I found that changing the version of the storyboard to be saved as xcode < 8, seem to solve the issue, but this has to be made every time the storyboard is opened, this can be used as a temporary solution until xcode beta goes to oficial. another solution is run the project using the current xcode beta-3.

To change the storyboard version go to **info** tab once opened and choose the option highlighted below.

<img width="261" alt="screen shot 2016-10-23 at 12 31 22 pm" src="https://cloud.githubusercontent.com/assets/2993852/19627755/b1184512-991c-11e6-9577-9d4c84e3c316.png">

Please let me know if that worked for you.

**Comment by imyellow** [comment]
@xhamr it works, but when I open the xib or storyboard again, the value will set to Xcode(8.0) auto, you must change it every times you opened it.
I hope you can completely fix it, thanks.

**Comment by ws4715535** [comment]
@xhamr seems work without storyBoard/xib ~
